// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: car-info.proto

package main.java.protobuf;

public final class CarInfo {
  private CarInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoCar_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoCar_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016car-info.proto\"\261\001\n\010ProtoCar\022\n\n\002id\030\001 \001(" +
      "\005\022\014\n\004name\030\002 \001(\t\022\r\n\005title\030\003 \001(\t\022 \n\006corpus" +
      "\030\004 \001(\0162\020.ProtoCar.Corpus\"Z\n\006Corpus\022\r\n\tUN" +
      "IVERSAL\020\000\022\007\n\003WEB\020\001\022\n\n\006IMAGES\020\002\022\t\n\005LOCAL\020" +
      "\003\022\010\n\004NEWS\020\004\022\014\n\010PRODUCTS\020\005\022\t\n\005VIDEO\020\006B\026\n\022" +
      "main.java.protobufP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ProtoCar_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtoCar_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoCar_descriptor,
        new java.lang.String[] { "Id", "Name", "Title", "Corpus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
